# Generated by Django 2.2.4 on 2019-08-10 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring_system', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scoringcriteria',
            old_name='point_value',
            new_name='max_point_value',
        ),
    ]
