# Generated by Django 2.2.4 on 2019-08-10 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring_system', '0002_auto_20190810_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringcriteria',
            name='score_type',
            field=models.CharField(default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scoringcriteria',
            name='task_description',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
