# Generated by Django 2.2.4 on 2019-08-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring_system', '0003_auto_20190810_0512'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_points', models.SmallIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='scoringcriteria',
            name='score_type',
            field=models.CharField(max_length=2),
        ),
        migrations.AddField(
            model_name='team',
            name='match_results',
            field=models.ManyToManyField(to='scoring_system.MatchResult'),
        ),
    ]
