# Generated by Django 2.2.2 on 2019-08-30 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring_system', '0004_auto_20190810_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoringcategory',
            name='category_image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
