# Generated by Django 2.2.2 on 2019-08-30 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring_system', '0005_auto_20190830_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoringcategory',
            name='category_image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
