# Generated by Django 2.2.2 on 2019-08-31 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring_system', '0006_auto_20190830_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoringcriteria',
            name='max_point_value',
        ),
        migrations.AddField(
            model_name='scoringcriteria',
            name='max_input',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='scoringcriteria',
            name='prerequisite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scoringcriteria',
            name='score_multiplier',
            field=models.SmallIntegerField(default=99),
            preserve_default=False,
        ),
    ]
