# Generated by Django 2.2.2 on 2019-08-31 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring_system', '0007_auto_20190830_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoringcriteria',
            name='max_input',
        ),
    ]
