# Generated by Django 2.2.2 on 2019-08-31 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring_system', '0008_remove_scoringcriteria_max_input'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoringcriteria',
            name='score_multiplier',
        ),
    ]
