# Generated by Django 2.2.2 on 2019-08-31 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring_system', '0009_remove_scoringcriteria_score_multiplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoringcriteria',
            name='prerequisite',
        ),
    ]
