# Generated by Django 2.2.2 on 2019-08-31 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring_system', '0010_remove_scoringcriteria_prerequisite'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringcriteria',
            name='max_int',
            field=models.SmallIntegerField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='scoringcriteria',
            name='prerequisite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scoringcriteria',
            name='score_multiplier',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
