# Generated by Django 2.2.2 on 2019-08-31 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring_system', '0011_auto_20190830_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scoringcriteria',
            old_name='max_int',
            new_name='max_input',
        ),
    ]
