# Generated by Django 2.2.4 on 2019-10-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring_system', '0012_auto_20190830_2015'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoringcriteria',
            name='t_option1',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='scoringcriteria',
            name='t_option2',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='scoringcriteria',
            name='t_option3',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
