# Generated by Django 2.2.4 on 2019-10-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring_system', '0015_auto_20191019_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoringcategory',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
