# Generated by Django 2.2 on 2019-11-07 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring_system', '0017_livescore_thread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoringcriteria',
            name='t_option1',
        ),
        migrations.RemoveField(
            model_name='scoringcriteria',
            name='t_option2',
        ),
        migrations.RemoveField(
            model_name='scoringcriteria',
            name='t_option3',
        ),
        migrations.RemoveField(
            model_name='team',
            name='match_results',
        ),
        migrations.RemoveField(
            model_name='team',
            name='points',
        ),
        migrations.AddField(
            model_name='scoringcriteria',
            name='default',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='match1',
            field=models.CharField(blank=True, default='/', max_length=4),
        ),
        migrations.AddField(
            model_name='team',
            name='match2',
            field=models.CharField(blank=True, default='/', max_length=4),
        ),
        migrations.AddField(
            model_name='team',
            name='match3',
            field=models.CharField(blank=True, default='/', max_length=4),
        ),
        migrations.AlterField(
            model_name='team',
            name='number',
            field=models.CharField(max_length=5),
        ),
        migrations.DeleteModel(
            name='LiveScore',
        ),
        migrations.DeleteModel(
            name='MatchResult',
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
