# Generated by Django 2.2.3 on 2020-01-23 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring_system', '0018_auto_20191107_1732'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventUser',
        ),
    ]
