# Generated by Django 2.2.3 on 2020-01-23 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring_system', '0020_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='red_team',
        ),
        migrations.AddField(
            model_name='match',
            name='teams',
            field=models.ManyToManyField(to='scoring_system.Team'),
        ),
    ]
