# Generated by Django 2.2.3 on 2020-01-24 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring_system', '0021_auto_20200123_0311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='match_number',
            new_name='round_number',
        ),
        migrations.AddField(
            model_name='match',
            name='blue_number',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='red_number',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
