# Generated by Django 2.2.3 on 2020-01-24 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring_system', '0023_match_match_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='match_number',
        ),
    ]
