# Generated by Django 2.2.3 on 2020-01-25 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring_system', '0024_remove_match_match_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='blue_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='red_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
