# Generated by Django 2.2.3 on 2020-01-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring_system', '0026_match_match_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='blue_submitted',
        ),
        migrations.RemoveField(
            model_name='match',
            name='red_submitted',
        ),
        migrations.AddField(
            model_name='match',
            name='total_submitted',
            field=models.SmallIntegerField(default=0),
        ),
    ]
