# Generated by Django 2.2.3 on 2020-01-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring_system', '0027_auto_20200125_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='highest_score',
            field=models.CharField(blank=True, default='/', max_length=4),
        ),
    ]
