# Generated by Django 2.2.3 on 2020-03-24 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring_system', '0028_team_highest_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f1_enabled', models.BooleanField(blank=True, default=True)),
                ('f1_t1_color', models.CharField(blank=True, default='Red', max_length=10)),
                ('f1_t2_color', models.CharField(blank=True, default='Blue', max_length=10)),
                ('f2_enabled', models.BooleanField(blank=True, default=False)),
                ('f2_t1_color', models.CharField(blank=True, default='Green', max_length=10)),
                ('f2_t2_color', models.CharField(blank=True, default='Yellow', max_length=10)),
                ('f3_enabled', models.BooleanField(blank=True, default=False)),
                ('f3_t1_color', models.CharField(blank=True, default='Pink', max_length=10)),
                ('f3_t2_color', models.CharField(blank=True, default='Purple', max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='match',
            old_name='red_number',
            new_name='t1_number',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='blue_number',
            new_name='t2_number',
        ),
        migrations.AddField(
            model_name='match',
            name='field_number',
            field=models.SmallIntegerField(default=2),
            preserve_default=False,
        ),
    ]
